In [12]:
import pandas as pd
df = pd.read_csv('D:\\DATA ANALYSIS\\OLA PROJECT 2\\Bookings.csv')

In [13]:
df.head()

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Unnamed: 19
0,07-03-2026,0.07,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,NaN,Personal & Car related issue,NaN,NaN,444.0,NaN,0.0,NaN,NaN,NaN
1,03-03-2026,18.29,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,NaN,NaN,No,NaN,158.0,Cash,13.0,4.1,4.0,NaN
2,20-03-2026,5.39,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,NaN,NaN,No,NaN,386.0,UPI,40.0,4.2,4.8,NaN
3,30-03-2026,16.42,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,Driver is not moving towards pickup location,NaN,NaN,NaN,384.0,NaN,0.0,NaN,NaN,NaN
4,08-03-2026,12.26,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,NaN,NaN,No,NaN,822.0,Credit Card,45.0,4.0,3.0,NaN

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 103025 entries, 0 to 103024
Data columns (total 20 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Date                        103024 non-null  str
 1   Time                        103024 non-null  float64
 2   Booking_ID                  103024 non-null  str
 3   Booking_Status              103024 non-null  str
 4   Customer_ID                 103024 non-null  str
 5   Vehicle_Type                103024 non-null  str
 6   Pickup_Location             103024 non-null  str
 7   Drop_Location               103024 non-null  str
 8   V_TAT                       63967 non-null   float64
 9   C_TAT                       63967 non-null   float64
 10  Canceled_Rides_by_Customer  10499 non-null   str
 11  Canceled_Rides_by_Driver    18434 non-null   str
 12  Incomplete_Rides            63967 non-null   str
 13  Incomplete_Rides_Reason     3926 non-null    str
 14  Booking_Value               103024 non-null  float64
 15  Payment_Method              63967 non-null   str
 16  Ride_Distance               103024 non-null  float64
 17  Driver_Ratings              63967 non-null   float64
 18  Customer_Rating             63967 non-null   float64
 19  Unnamed: 19                 0 non-null       float64
dtypes: float64(8), str(12)
memory usage: 15.7 MB

In [15]:
df.describe()

,Time,V_TAT,C_TAT,Booking_Value,Ride_Distance,Driver_Ratings,Customer_Rating,Unnamed: 19
count,103024.000000,63967.000000,63967.000000,103024.000000,103024.000000,63967.000000,63967.000000,0.0
mean,11.798789,170.876952,84.873372,548.751883,14.189927,3.997457,3.998313,NaN
std,6.926777,80.803640,36.005100,536.541221,15.776270,0.576834,0.578957,NaN
min,0.000000,35.000000,25.000000,100.000000,0.000000,3.000000,3.000000,NaN
25%,6.010000,98.000000,55.000000,242.000000,0.000000,3.500000,3.500000,NaN
50%,12.000000,168.000000,85.000000,386.000000,8.000000,4.000000,4.000000,NaN
75%,17.590000,238.000000,115.000000,621.000000,26.000000,4.500000,4.500000,NaN
max,23.590000,308.000000,145.000000,2999.000000,49.000000,5.000000,5.000000,NaN

In [16]:
df.isnull().sum()

Date                               1
Time                               1
Booking_ID                         1
Booking_Status                     1
Customer_ID                        1
Vehicle_Type                       1
Pickup_Location                    1
Drop_Location                      1
V_TAT                          39058
C_TAT                          39058
Canceled_Rides_by_Customer     92526
Canceled_Rides_by_Driver       84591
Incomplete_Rides               39058
Incomplete_Rides_Reason        99099
Booking_Value                      1
Payment_Method                 39058
Ride_Distance                      1
Driver_Ratings                 39058
Customer_Rating                39058
Unnamed: 19                   103025
dtype: int64

In [17]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [18]:
df.columns

Index(['date', 'time', 'booking_id', 'booking_status', 'customer_id',
       'vehicle_type', 'pickup_location', 'drop_location', 'v_tat', 'c_tat',
       'canceled_rides_by_customer', 'canceled_rides_by_driver',
       'incomplete_rides', 'incomplete_rides_reason', 'booking_value',
       'payment_method', 'ride_distance', 'driver_ratings', 'customer_rating',
       'unnamed:_19'],
      dtype='str')

In [26]:
from sqlalchemy import create_engine
import urllib.parse
username = "postgres"
password = urllib.parse.quote_plus("Suraj@2690")
host = "localhost"
port ="5432"
database = "OLA"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

table_name = "Booking_Data"
df.to_sql(table_name,engine,if_exists = "replace",index= False)


print(f"Data Successfully Loaded into table '{table_name}' in Database '{database}'")

Data Successfully Loaded into table 'Booking_Data' in Database 'OLA'